version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - REDIS_URL=redis://:redis@redis:6379
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: /bin/sh -c "redis-server --requirepass redis"
    volumes: 
      - redis:/data
volumes:
  redis: