# Generated by Django 5.0.4 on 2025-02-26 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productimage_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproductpage',
            name='sku',
        ),
        migrations.AddField(
            model_name='shopproductpage',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
